"""adding manager-club relationship

Revision ID: 036950ad6cdf
Revises: 44ddfb219b36
Create Date: 2026-07-15 17:56:52.486289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036950ad6cdf'
down_revision: Union[str, Sequence[str], None] = '44ddfb219b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('club_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'managers', 'clubs', ['club_id'], ['id'])
    op.drop_column('managers', 'current_team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('current_team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'managers', type_='foreignkey')
    op.drop_column('managers', 'club_id')
    # ### end Alembic commands ###
