"""add players table

Revision ID: 55520e6b1435
Revises: 036950ad6cdf
Create Date: 2026-07-15 21:16:24.643609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55520e6b1435'
down_revision: Union[str, Sequence[str], None] = '036950ad6cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('known_as', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('national_team_id', sa.Integer(), nullable=True),
    sa.Column('primary_position', sa.String(length=5), nullable=False),
    sa.Column('secondary_position', sa.String(length=5), nullable=False),
    sa.Column('preferred_foot', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('market_value', sa.BigInteger(), nullable=True),
    sa.Column('contract_until', sa.Date(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['national_team_id'], ['national_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
