"""fix player nullable fields v2

Revision ID: b83a46e62a5e
Revises: e21b996fbe04
Create Date: 2026-07-15 22:34:14.233520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83a46e62a5e'
down_revision: Union[str, Sequence[str], None] = 'e21b996fbe04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'secondary_position',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'secondary_position',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    # ### end Alembic commands ###
