"""fix player nullable fields

Revision ID: e21b996fbe04
Revises: 55520e6b1435
Create Date: 2026-07-15 22:30:36.609946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21b996fbe04'
down_revision: Union[str, Sequence[str], None] = '55520e6b1435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'height_cm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'weight_kg',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'weight_kg',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'height_cm',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
